development:
  secret_key_base: 83a59e748363fd0cc667f4f7ffc611c316885c95864a26302ceffb05fa550cfe29b501347175fcbef5e14ce9fb4dceb0468353e85acfd1fb13aee8da9d36de78
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>
